# Generated by Django 6.0.4 on 2026-04-22 07:24

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SliderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Заголовок для слайда",
                        max_length=200,
                        verbose_name="Заголовок",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Отображать слайд на сайте",
                        verbose_name="Активно",
                    ),
                ),
                (
                    "my_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Чем меньше число, тем выше слайд",
                        verbose_name="Порядок сортировки",
                    ),
                ),
                (
                    "image",
                    filer.fields.image.FilerImageField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="slider_items",
                        to=settings.FILER_IMAGE_MODEL,
                        verbose_name="Изображение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Элемент слайда",
                "verbose_name_plural": "Элементы слайда",
                "ordering": ["my_order", "-id"],
            },
        ),
    ]
